CREATE table "person"
(
    id           int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username     varchar(100) UNIQUE NOT NULL,
    password     varchar             NOT NULL,
    display_name varchar(100)        NOT NULL,
    avatar       varchar
);

CREATE TABLE refresh_token
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    refresh_token VARCHAR(100) NOT NULL,
    username      VARCHAR(100) NOT NULL,
    CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES person (username) ON DELETE CASCADE
);

CREATE TABLE hoax
(
    id        SERIAL PRIMARY KEY,
    content   VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP    NOT NULL,
    creator   VARCHAR(100) REFERENCES person (username)
);